swagger: '2.0'
info:
  version: "1.1"
  title: 'API for Group Project'
  description: 'Communication between browser and AWS lambda function'
tags:
- name: administrator
  description: Admin-only calls
- name: participant
  description: Operations available to regular consumers
paths: 
  /playlists:
    get:
      tags:
      - participant
      summary: request a list of all playlists
      description: Returns a list of all playlists
      operationId: getPlaylistList
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: list of playlists returned
          schema: 
            $ref: '#/definitions/ListPlaylistsResponse'
    post:
      tags:
      - participant
      summary: requests to create a new playlist
      description: Creates a new playlist
      operationId: newPlaylist
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: NewPlaylistRequest
        description: Creates new Playlist
        required: false
        schema:
          $ref: '#/definitions/NewPlaylistRequest'
      responses:
        200:
          description: a new playlist has been added to the library
          schema:
            $ref: '#/definitions/NewPlaylistResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
        409:
          description: valid input but duplicate playlist
          schema:
            $ref: '#/definitions/ErrorResponse'
  /playlistRemove:
    post:
      tags:
      - participant
      summary: requests to delete an existing playlist
      description: Deletes a  playlist
      operationId: deletePlaylist
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DeletePlaylistRequest
        description: Deletes Playlist
        required: false
        schema:
          $ref: '#/definitions/DeletePlaylistRequest'
      responses:
        200:
          description: a playlist has been removed from the library
          schema:
            $ref: '#/definitions/DeletePlaylistResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /videoSegments:
    get:
      tags:
      - participant
      summary: request a list of video segments in the library
      description: Returns a list of all video segments in the library
      operationId: getVideoSegmentsList
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: list of video segments in the library returned
          schema:
            $ref: '#/definitions/ListVideoSegmentsRequest'
    post:
      tags:
      - participant
      summary: requests to upload a video segment to the library
      description: Uploads a new video segment to the local library
      operationId: newVideoSegment
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: NewVideoSegmentRequest
        description: Adds a video segment to the library
        required: false
        schema:
          $ref: '#/definitions/NewVideoSegmentRequest'
      responses:
        200:
          description: video segment is uploaded
          schema:
            $ref: '#/definitions/NewVideoSegmentResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
        409:
          description: valid input but duplicate video
          schema:
            $ref: '#/definitions/ErrorResponse'
  /playlistVideoSegments:
    post:
      tags:
      - participant
      summary: request a list of video segments in the playlist
      description: Returns a list of all video segments in the playlist
      operationId: getVideoSegmentsListInPlaylist
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: ListPlaylistVideoSegmentsRequest
        description: lists all of the video segments in the playlist
        required: false
        schema:
          $ref: '#/definitions/ListPlaylistVideoSegmentsRequest'
      responses:
        200:
          description: list of video segments returned
          schema:
            $ref: '#/definitions/ListPlaylistVideoSegmentsResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /playlistVideoSegmentAppend:  
    post:
      tags:
      - participant
      summary: requests to add a video segment to a playlist
      description: Adds video segment onto the end of a playlist's list of video segments
      operationId: appendPlaylist
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: AppendPlaylistRequest
        description: Adds a video segment to the end of a playlist
        required: false
        schema:
          $ref: '#/definitions/AppendPlaylistRequest'
      responses:
        200:
          description: a video segment has been appended to the playlist
          schema:
            $ref: '#/definitions/AppendPlaylistResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /playlistVideoSegmentRemove:
    post:
      tags:
      - participant
      summary: requests to remove a video segment from the playlist
      description: Remove a video segment from the playlist
      operationId: removeVideoSegmentFromPlaylist
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DeletePlaylistVideoSegmentRequest
        description: Deletes a video segment from the playlist
        required: false
        schema:
          $ref: '#/definitions/DeletePlaylistVideoSegmentRequest'
      responses:
        200:
          description: video segment removed from playlist
          schema:
            $ref: '#/definitions/DeletePlaylistVideoSegmentResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /videoSegmentRemove:
    post:
      tags:
      - participant
      summary: requests to delete a video segment from the local library
      description: Deletes a video segment from the local library
      operationId: deleteVideoSegment
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DeleteVideoSegmentRequest
        description: Deletes a video segment
        required: false
        schema:
          $ref: '#/definitions/DeleteVideoSegmentRequest'
      responses:
        200:
          description: video segment has been deleted from the library
          schema:
            $ref: '#/definitions/DeleteVideoSegmentResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /searchVideoSegments: 
    post:
      tags:
      - participant
      summary: request to search video segments
      description: Requests to create a search from base64 string title and/or base64 string character
      operationId: searchVideoSegments
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentSearchRequest
        description: Search for a video segment in local and remote libraries
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentSearchRequest'
      responses:
        200:
          description: search completed
          schema:
            $ref: '#/definitions/VideoSegmentSearchResponse'
        400:
          description: invalid input, search invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /videoSegmentRemoteStatus:
    post:
      tags:
        - administrator
      summary: requests that video segment remote availability is toggled
      description: Requests that video segment remote availability is toggled
      operationId: requestAvailable
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoRemoteStatusRequest
        description: Toggles video segment remote availability
        required: false
        schema:
          $ref: '#/definitions/RemoteStatusRequest'
      responses:
        200:
          description: video segment marked available
          schema:
            $ref: '#/definitions/RemoteStatusResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
  /remoteLibrary:
    post:
      tags:
        - administrator
      summary: requests that remote library is added
      description: Requests that remote library is added
      operationId: requestAddRemoteLibrary
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: RemoteLibraryAddRequest
        description: Adds remote library
        required: false
        schema:
          $ref: '#/definitions/RemoteLibraryAddRequest'
      responses:
        200:
          description: remote library unselected
          schema:
            $ref: '#/definitions/RemoteLibraryAddResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
        409:
          description: remote library has already been registered
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
        - administrator
      summary: request a list of all remote libraries
      description: Returns a list of all remote libraries
      operationId: getRemoteLibraries
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: list of remote libraries returned
          schema:
            $ref: '#/definitions/ListRemoteLibraryResponse'
  /remoteLibraryRemove:
    post:
      tags:
        - administrator
      summary: requests that remote library is removed
      description: Requests that remote library is removed
      operationId: requestRemoveRemoteLibrary
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: RemoteLibraryRemoveRequest
        description: Removes remote library
        required: false
        schema:
          $ref: '#/definitions/RemoteLibraryRemoveRequest'
      responses:
        200:
          description: remote library removed
          schema:
            $ref: '#/definitions/RemoteLibraryRemoveResponse'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  NewPlaylistRequest:
    type: object
    required:
    - playlistName
    properties:
      playlistName:
        type: string
  NewPlaylistResponse:
    type: object
    required:
    - name
    properties:
      name:
        type: string
  DeletePlaylistRequest:
    type: object
    required:
    - playlistNames
    properties:
      playlistNames:
        type: array
        items:
          type: string
  DeletePlaylistResponse:
    type: object
    required:
    - PlaylistName
    properties:
      playlistName:
        type: string
  AppendPlaylistRequest:
    type: object
    required:
    - playlistName
    - videoUrls
    properties:
      playlistName:
        type: string
      videoUrls:
        type: array
        items:
          type: string
  AppendPlaylistResponse:
    type: object
    required:
    - playlistName
    properties:
      playlistName:
        type: string
  NewVideoSegmentRequest:
    type: object
    required:
    - title
    - character
    - filepath
    properties:
      title:
        type: string
      character:
        type: string
      filepath:
        type: string
  NewVideoSegmentResponse:
    type: object
    required:
    - url
    properties:
      url:
        type: string
  DeleteVideoSegmentRequest:
    type: object
    required:
    - videoUrls
    properties:
      videoUrls:
        type: array
        items:
          type: string
  DeleteVideoSegmentResponse:
    type: object
    required: 
    - videoUrl
    properties:
      videoUrl:
        type: string
  VideoSegmentSearchRequest:
    type: object
    required:
    - title
    - character
    properties:
      title:
        type: string
      character:
        type: string
  VideoSegmentSearchResponse:
    type: object
    required:
    - listOfSegments
    properties:
      listOfSegments:
        type: array
        items:
          $ref: '#/definitions/VideoSegment'
  RemoteStatusRequest:
    type: object
    required:
    - checkboxes
    - videoUrls
    properties:
      checkboxes:
        type: array
        items:
          type: boolean
      videoUrls:
        type: array
        items:
          type: string
  RemoteStatusResponse:
    type: object
    required:
    - videoUrls
    properties:
      videoUrls:
        type: array
        items:
          type: string
  RemoteLibraryAddRequest:
    type: object
    required:
    - url
    properties:
      url:
        type: string
  RemoteLibraryAddResponse:
    type: object
    required:
    - url
    properties:
      url:
        type: string
  RemoteLibraryRemoveRequest:
    type: object
    required:
    - urls
    properties:
      urls:
        type: array
        items:
          type: string
  RemoteLibraryRemoveResponse:
    type: object
    required:
    - urls
    properties:
      urls:
        type: array
        items:
          type: string
  ListPlaylistVideoSegmentsRequest:
    type: object
    required: 
    - playlistName
    properties:
      playlistName:
        type: string
  ListPlaylistVideoSegmentsResponse:
    type: object
    required:
    - listOfSegments
    - playlist
    properties:
      listOfSegments:
        type: array
        items:
          $ref: '#/definitions/VideoSegment'
      playlist:
        $ref: '#/definitions/Playlist'
  DeletePlaylistVideoSegmentRequest:
    type: object
    required:
    - playlistName
    - videoSegmentIndices
    - videoSegmentUrls
    properties:
      playlistName:
        type: string
      videoSegmentIndices:
        type: array
        items:
          type: integer
      videoSegmentUrls:
        type: array
        items:
          type: string
  DeletePlaylistVideoSegmentResponse:
    type: object
    required:
    - videoSegmentUrls
    properties:
      videoSegmentUrls:
        type: array
        items:
          type: string
  ListPlaylistsResponse:
    type: object
    required:
    - listOfPlaylists
    properties:
      listOfPlaylists:
        type: array
        items:
          $ref: '#/definitions/Playlist'
  ListVideoSegmentsRequest:
    type: object
    required:
    - listOfSegments
    properties:
      listofSegments:
        type: array
        items:
          $ref: '#/definitions/VideoSegment'
  ListRemoteLibraryResponse:
    type: object
    required:
    - listOfRemoteLibraries
    properties:
      listOfRemoteLibraries:
        type: array
        items:
          $ref: '#/definitions/RemoteLibrary'
  ErrorResponse:
    type: object
    required:
    - errorMessage
    properties:
      errorMessage:
        type: string
  VideoSegment:
    type: object
    required:
    - title
    - character
    - url
    - remoteStatus
    properties:
      title:
        type: string
      character:
        type: string
      url:
        type: string
      remoteStatus:
        type: boolean
  Playlist:
    type: object
    required:
    - name
    properties:
      name:
        type: string
  RemoteLibrary:
    type: object
    required:
    - url
    properties:
      url:
        type: string

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Vision-of-Hope/vision_of_hope_surpassed/1.0
schemes:
 - https